# GitHub <https://github.com/rust-lang/rustfmt/blob/master/README.md#license>
# Configurator <https://rust-lang.github.io/rustfmt/?version=master>

unstable_features            = true
edition                      = "2018"

brace_style                  = "AlwaysNextLine"
imports_layout               = "Vertical"
indent_style                 = "Block"

combine_control_expr         = false
reorder_imports              = false
reorder_modules              = false

condense_wildcard_suffixes   = true
error_on_line_overflow       = true
error_on_unformatted         = true
fn_single_line               = true
format_code_in_doc_comments  = true
format_macro_bodies          = true
format_macro_matchers        = true
format_strings               = true
hard_tabs                    = true
match_block_trailing_comma   = true
merge_imports                = true
normalize_comments           = true
normalize_doc_attributes     = true
reorder_impl_items           = true
use_field_init_shorthand     = true
wrap_comments                = true

blank_lines_upper_bound      = 1
comment_width                = 77
enum_discrim_align_threshold = 35
inline_attribute_width       = 60
max_width                    = 77
struct_field_align_threshold = 35
