site_name: unCore
repo_name: uncore
repo_url: https://github.com/aendeavor/uncore
nav:
  - Welcome: index.md
  - Development: development.md
  - Changelog: changelog.md
theme:
  name: material
  language: en
  font: false
  favicon: images/logo.ico
  logo: images/logo.png
  features:
    - navigation.instant
    - toc.autohide
  palette:
    scheme: default
    primary: white
    accent: amber
  icon:
    repo: fontawesome/brands/github
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.snippets
  - admonition
  - toc:
      toc_depth: 4
  - pymdownx.highlight:
      linenums: true
